name: Ruby CI

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '**/*'

jobs:
  test:

    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby: [3.0, 3.1, 3.2]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: bundle install

      - name: Build
        run: bundle exec rake build
    
      - name: Load test data
        run: bundle exec rake test_refreshed_data
    
      - name: Run tests
        run: bundle exec rspec
